package com.ikegami99.jinkaku.ui

import android.content.Intent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.ikegami99.jinkaku.JinkakuViewModel
import com.ikegami99.jinkaku.data.ROLE_USER

@Composable fun JinkakuApp(vm:JinkakuViewModel){val ui by vm.ui.collectAsStateWithLifecycle();var settings by remember{mutableStateOf(false)};val snackbar=remember{SnackbarHostState()};val context=androidx.compose.ui.platform.LocalContext.current;LaunchedEffect(ui.error,ui.notice){val text=ui.error?:ui.notice;if(text!=null){snackbar.showSnackbar(text);vm.clearMessagesNotice()}};MaterialTheme(colorScheme=lightColorScheme()){Scaffold(snackbarHost={SnackbarHost(snackbar)},topBar={Surface(shadowElevation=1.dp){Row(Modifier.fillMaxWidth().statusBarsPadding().padding(16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Jinkaku",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("${ui.runtimeStatus}  •  Memory ${ui.memoryCount}",style=MaterialTheme.typography.labelMedium)};TextButton(onClick={settings=!settings}){Text(if(settings)"チャット" else "設定")}}}}){padding->if(settings)SettingsScreen(vm,Modifier.padding(padding)){file,mime->val uri=FileProvider.getUriForFile(context,"${context.packageName}.files",file);context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type=mime;putExtra(Intent.EXTRA_STREAM,uri);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)},"共有"))}else ChatScreen(vm,Modifier.padding(padding))}}}

@Composable private fun ChatScreen(vm:JinkakuViewModel,modifier:Modifier=Modifier){val ui by vm.ui.collectAsStateWithLifecycle();var input by remember{mutableStateOf("")};Column(modifier.fillMaxSize().imePadding()){LazyColumn(Modifier.weight(1f).fillMaxWidth(),contentPadding=PaddingValues(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(ui.messages,key={it.id}){m->Row(Modifier.fillMaxWidth(),horizontalArrangement=if(m.role==ROLE_USER)Arrangement.End else Arrangement.Start){Surface(shape=RoundedCornerShape(18.dp),tonalElevation=if(m.role==ROLE_USER)3.dp else 1.dp,modifier=Modifier.fillMaxWidth(0.88f)){Text(m.content,Modifier.padding(14.dp))}}};if(ui.busy){item{Surface(shape=RoundedCornerShape(18.dp),tonalElevation=1.dp){Column(Modifier.padding(14.dp)){if(ui.thinking)Text("Thinking…",style=MaterialTheme.typography.labelMedium);if(ui.generatingText.isNotBlank())Text(ui.generatingText)}}}}};HorizontalDivider();Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.Bottom){OutlinedTextField(value=input,onValueChange={input=it},modifier=Modifier.weight(1f),placeholder={Text("メッセージ")},maxLines=6);Spacer(Modifier.width(8.dp));if(ui.busy)Button(onClick=vm::stopGeneration){Text("停止")}else Button(onClick={val t=input;input="";vm.send(t)},enabled=input.isNotBlank()){Text("送信")}}}}

@Composable private fun SettingsScreen(vm:JinkakuViewModel,modifier:Modifier=Modifier,share:(java.io.File,String)->Unit){val ui by vm.ui.collectAsStateWithLifecycle();LazyColumn(modifier.fillMaxSize(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{Text("モデル",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};item{ModelCard("Gemma 4 E4B HauhauCS Q4_K_M",ui.e4bInstalled,ui.e4bDownload?.progress,vm::downloadE4B,vm::deleteE4B)};item{ModelCard("Gemma 4 E2B LiteRT-LM",ui.e2bInstalled,ui.e2bDownload?.progress,vm::downloadE2B,vm::deleteE2B)};item{Text("Context",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf(4096L,8192L,16384L,32768L).forEach{size->FilterChip(selected=ui.contextSize==size,onClick={vm.setContext(size)},label={Text("${size/1024}K")})}}};item{Text("長期メモリ",fontWeight=FontWeight.Bold);Text("Active: ${ui.memoryCount}件。E2Bは会話中には常駐せず、アイドル時に整理します。");Button(onClick=vm::runMemoryMaintenance,enabled=ui.e2bInstalled&&!ui.busy){Text("今すぐ記憶を整理")}};item{Text("メンテナンス",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick={share(vm.exportLog(),"text/plain")}){Text("ログを書き出す")};OutlinedButton(onClick={share(vm.createBackup(),"application/zip")}){Text("バックアップ")}};Text("ログは常時ファイルへ追記し、共有前にflush/syncします。空ログは生成しません。",style=MaterialTheme.typography.bodySmall)};item{Text("アプリ更新",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick=vm::checkUpdate){Text("更新確認")};if(ui.updateInfo!=null)Button(onClick=vm::downloadUpdate){Text("APK取得")};OutlinedButton(onClick=vm::installUpdate){Text("インストール")}}};item{Text("Embedding",fontWeight=FontWeight.Bold);Text("MVPでは256次元の完全ローカルHashing Embedding + 固有名詞検索を使用。EmbeddingGemma 300MはHugging Faceの利用同意が必要なため、次段階で差し替え可能な構造にしています。",style=MaterialTheme.typography.bodySmall)};item{Spacer(Modifier.height(32.dp))}}}

@Composable private fun ModelCard(name:String,installed:Boolean,progress:Float?,download:()->Unit,delete:()->Unit){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(name,fontWeight=FontWeight.SemiBold);Text(if(installed)"インストール済み" else "未インストール");if(!installed&&progress!=null&&progress>0f&&progress<1f)LinearProgressIndicator(progress={progress},modifier=Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){if(!installed)Button(onClick=download){Text("ダウンロード")}else OutlinedButton(onClick=delete){Text("削除")}}}}}
