from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"anchor not found: {label}")
    return text.replace(old, new, 1)


def patch_ui() -> None:
    path = Path("app/src/main/java/com/ikegami99/jinkaku/ui/ModernJinkakuApp.kt")
    text = path.read_text(encoding="utf-8")

    if "EDGE_GLOSS_V050" in text:
        print("EDGE_GLOSS_V050 already applied")
        return
    if "KAWAII_GLASS_V049" not in text:
        raise RuntimeError("v049 kawaii glass patch must run before v050")

    if "import androidx.compose.ui.draw.drawBehind\n" not in text:
        text = replace_once(
            text,
            "import androidx.compose.ui.draw.clip\n",
            "import androidx.compose.ui.draw.clip\nimport androidx.compose.ui.draw.drawBehind\n",
            "drawBehind import",
        )

    old_top = '''                        // CANDY_GLASS_V048: liquid-glass style. The aurora stays visible\n                        // through the bar; white highlights and color refraction provide\n                        // the glass edge instead of an opaque dark strip.\n                        // KAWAII_GLASS_V049: clearer glass with a brighter specular sheen.\n                        modifier = Modifier\n                            .background(\n                                Brush.horizontalGradient(\n                                    listOf(\n                                        MaterialTheme.colorScheme.primary.copy(alpha = if (darkMode) 0.07f else 0.06f),\n                                        Color.Transparent,\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = if (darkMode) 0.06f else 0.05f),\n                                        Color.Transparent\n                                    )\n                                )\n                            )\n                            .background(\n                                Brush.verticalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.24f else 0.38f),\n                                        Color.White.copy(alpha = if (darkMode) 0.08f else 0.14f),\n                                        Color.Transparent,\n                                        Color.White.copy(alpha = if (darkMode) 0.04f else 0.07f)\n                                    )\n                                )\n                            )\n                            .border(\n                                width = 0.7.dp,\n                                brush = Brush.horizontalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.52f else 0.76f),\n                                        MaterialTheme.colorScheme.primary.copy(alpha = 0.18f),\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = 0.16f),\n                                        Color.White.copy(alpha = if (darkMode) 0.34f else 0.58f)\n                                    )\n                                ),\n                                shape = RoundedCornerShape(0.dp)\n                            ),\n'''
    new_top = '''                        // CANDY_GLASS_V048: liquid-glass style. The aurora stays visible\n                        // through the bar; white highlights and color refraction provide\n                        // the glass edge instead of an opaque dark strip.\n                        // KAWAII_GLASS_V049: clearer glass with a brighter specular sheen.\n                        // EDGE_GLOSS_V050: only the chat-facing bottom edge is drawn.\n                        modifier = Modifier\n                            .background(\n                                Brush.horizontalGradient(\n                                    listOf(\n                                        MaterialTheme.colorScheme.primary.copy(alpha = if (darkMode) 0.055f else 0.045f),\n                                        Color.Transparent,\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = if (darkMode) 0.050f else 0.040f),\n                                        Color.Transparent\n                                    )\n                                )\n                            )\n                            .background(\n                                Brush.verticalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.38f else 0.52f),\n                                        Color.White.copy(alpha = if (darkMode) 0.14f else 0.21f),\n                                        Color.Transparent,\n                                        Color.White.copy(alpha = if (darkMode) 0.035f else 0.055f)\n                                    )\n                                )\n                            )\n                            .background(\n                                Brush.radialGradient(\n                                    colors = listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.23f else 0.34f),\n                                        Color.Transparent\n                                    ),\n                                    center = Offset(170f, -30f),\n                                    radius = 650f\n                                )\n                            )\n                            .drawBehind {\n                                drawLine(\n                                    color = Color.White.copy(alpha = if (darkMode) 0.34f else 0.55f),\n                                    start = Offset(0f, size.height - 0.5.dp.toPx()),\n                                    end = Offset(size.width, size.height - 0.5.dp.toPx()),\n                                    strokeWidth = 0.7.dp.toPx()\n                                )\n                            },\n'''
    text = replace_once(text, old_top, new_top, "top chat-facing edge + gloss")

    old_bottom = '''        Surface(\n            // FINISH_V046: continuous composer band through the gesture/navigation area.\n            // CANDY_GLASS_V048: transparent liquid-glass composer instead of a black slab.\n            // KAWAII_GLASS_V049: more transparent with a glossy top highlight.\n            color = Color.Transparent,\n            contentColor = MaterialTheme.colorScheme.onSurface,\n            tonalElevation = 0.dp,\n            modifier = Modifier\n                .fillMaxWidth()\n                .background(\n                    Brush.horizontalGradient(\n                        listOf(\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.045f),\n                            Color.Transparent,\n                            MaterialTheme.colorScheme.secondary.copy(alpha = 0.040f)\n                        )\n                    )\n                )\n                .background(\n                    Brush.verticalGradient(\n                        listOf(\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.18f else 0.28f),\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.05f else 0.08f),\n                            Color.Transparent,\n                            Color.White.copy(alpha = 0.025f)\n                        )\n                    )\n                )\n                .border(\n                    width = 0.7.dp,\n                    brush = Brush.horizontalGradient(\n                        listOf(\n                            Color.White.copy(alpha = 0.52f),\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.16f),\n                            MaterialTheme.colorScheme.secondary.copy(alpha = 0.15f),\n                            Color.White.copy(alpha = 0.26f)\n                        )\n                    ),\n                    shape = RoundedCornerShape(0.dp)\n                )\n        ) {\n'''
    new_bottom = '''        Surface(\n            // FINISH_V046: continuous composer band through the gesture/navigation area.\n            // CANDY_GLASS_V048: transparent liquid-glass composer instead of a black slab.\n            // KAWAII_GLASS_V049: more transparent with a glossy top highlight.\n            // EDGE_GLOSS_V050: no side/bottom hairline; only the edge facing chat remains.\n            color = Color.Transparent,\n            contentColor = MaterialTheme.colorScheme.onSurface,\n            tonalElevation = 0.dp,\n            modifier = Modifier\n                .fillMaxWidth()\n                .background(\n                    Brush.horizontalGradient(\n                        listOf(\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.032f),\n                            Color.Transparent,\n                            MaterialTheme.colorScheme.secondary.copy(alpha = 0.030f)\n                        )\n                    )\n                )\n                .background(\n                    Brush.verticalGradient(\n                        listOf(\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.30f else 0.42f),\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.11f else 0.16f),\n                            Color.Transparent,\n                            Color.White.copy(alpha = 0.018f)\n                        )\n                    )\n                )\n                .background(\n                    Brush.radialGradient(\n                        colors = listOf(\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.20f else 0.30f),\n                            Color.Transparent\n                        ),\n                        center = Offset(180f, -20f),\n                        radius = 720f\n                    )\n                )\n                .drawBehind {\n                    drawLine(\n                        color = Color.White.copy(alpha = 0.52f),\n                        start = Offset(0f, 0.5.dp.toPx()),\n                        end = Offset(size.width, 0.5.dp.toPx()),\n                        strokeWidth = 0.7.dp.toPx()\n                    )\n                }\n        ) {\n'''
    text = replace_once(text, old_bottom, new_bottom, "bottom chat-facing edge + gloss")

    path.write_text(text, encoding="utf-8")
    print("Applied EDGE_GLOSS_V050: removed non-chat glass edges + stronger specular gloss")


if __name__ == "__main__":
    patch_ui()
