from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"anchor not found: {label}")
    return text.replace(old, new, 1)


def patch_ui() -> None:
    path = Path("app/src/main/java/com/ikegami99/jinkaku/ui/ModernJinkakuApp.kt")
    text = path.read_text(encoding="utf-8")

    if "KAWAII_GLASS_V049" in text:
        print("KAWAII_GLASS_V049 already applied")
        return
    if "CANDY_GLASS_V048" not in text:
        raise RuntimeError("v048 candy glass patch must run before v049")

    # KAWAII_GLASS_V049: cleaner pastel-candy palette with stronger separation.
    start = text.index("// UI_REFINEMENT_V047: complementary two-colour accent presets.")
    end = text.index("private fun modernColorScheme", start)
    accent_block = '''// UI_REFINEMENT_V047: complementary two-colour accent presets.\n// CANDY_GLASS_V048: higher-chroma candy colors and brighter containers.\n// KAWAII_GLASS_V049: sweeter pastel-candy pairs, including Pink × Purple.\nprivate data class ModernAccent(\n    val name: String,\n    val label: String,\n    val lightPrimary: Color,\n    val lightContainer: Color,\n    val darkPrimary: Color,\n    val darkContainer: Color,\n    val lightSecondary: Color,\n    val lightSecondaryContainer: Color,\n    val darkSecondary: Color,\n    val darkSecondaryContainer: Color,\n    val tertiary: Color\n)\n\nprivate val ModernAccents = listOf(\n    ModernAccent("Purple", "Purple × Lime", Color(0xFF9B5CFF), Color(0xFF8C5CFF), Color(0xFFC3A0FF), Color(0xFF7044D9), Color(0xFFA9D93F), Color(0xFFB7DF58), Color(0xFFD5F47A), Color(0xFF658A20), Color(0xFF61DFFF)),\n    ModernAccent("Blue", "Blue × Orange", Color(0xFF4E8BFF), Color(0xFF5A91FF), Color(0xFF8EB4FF), Color(0xFF3767C9), Color(0xFFFFA24A), Color(0xFFFFAD62), Color(0xFFFFC981), Color(0xFFA96524), Color(0xFFB487FF)),\n    ModernAccent("Cyan", "Cyan × Coral", Color(0xFF35D5EA), Color(0xFF43D5E7), Color(0xFF82EAF5), Color(0xFF218A9C), Color(0xFFFF746D), Color(0xFFFF817A), Color(0xFFFFA29B), Color(0xFFA44843), Color(0xFFFFC857)),\n    ModernAccent("Green", "Mint × Magenta", Color(0xFF34D7A5), Color(0xFF43D4A8), Color(0xFF7DECC7), Color(0xFF23886E), Color(0xFFFF61AD), Color(0xFFFF6FB8), Color(0xFFFF91CB), Color(0xFFA43A73), Color(0xFF74A3FF)),\n    ModernAccent("Orange", "Peach × Azure", Color(0xFFFF9166), Color(0xFFFF9A72), Color(0xFFFFB79A), Color(0xFFB85E40), Color(0xFF58A6FF), Color(0xFF69AEFF), Color(0xFF9CCBFF), Color(0xFF3971AA), Color(0xFFF47CE0)),\n    ModernAccent("Pink", "Pink × Teal", Color(0xFFFF5FA8), Color(0xFFFF6BAF), Color(0xFFFF91C2), Color(0xFFC73C82), Color(0xFF39D2C2), Color(0xFF4BD5C7), Color(0xFF80E9DE), Color(0xFF24877F), Color(0xFFA47BFF)),\n    ModernAccent("PinkPurple", "Pink × Purple", Color(0xFFFF5AAE), Color(0xFFFF68B5), Color(0xFFFF91CA), Color(0xFFC63A83), Color(0xFF9566FF), Color(0xFFA477FF), Color(0xFFC0A1FF), Color(0xFF6947B8), Color(0xFF65DFFF)),\n    ModernAccent("MintPeach", "Mint × Peach", Color(0xFF38DCC0), Color(0xFF48DFC6), Color(0xFF83F0DD), Color(0xFF258C7B), Color(0xFFFF9D8D), Color(0xFFFFAA9C), Color(0xFFFFC7BC), Color(0xFFA95D53), Color(0xFFFF73B8))\n)\n\n'''
    text = text[:start] + accent_block + text[end:]

    # Less muddy, more pastel-candy aurora. Keep the colours distinct instead of
    # stacking too much dark magenta over blue.
    replacements = [
        ("Color(0xFF071D3A)", "Color(0xFF0B2348)"),
        ("Color(0xFF20184D)", "Color(0xFF32245E)"),
        ("Color(0xFF45113D)", "Color(0xFF5A164B)"),
        ("Color(0xFFCEF7FF)", "Color(0xFFC9FAFF)"),
        ("Color(0xFFE9DBFF)", "Color(0xFFE8DBFF)"),
        ("Color(0xFFFFD7F0)", "Color(0xFFFFD4EC)"),
        ("MaterialTheme.colorScheme.primary.copy(alpha = if (darkMode) 0.62f else 0.50f)", "MaterialTheme.colorScheme.primary.copy(alpha = if (darkMode) 0.48f else 0.38f)"),
        ("Color(0xFF27E7FF).copy(alpha = if (darkMode) 0.56f else 0.44f)", "Color(0xFF5CEBFF).copy(alpha = if (darkMode) 0.44f else 0.34f)"),
        ("Color(0xFF9A62FF).copy(alpha = if (darkMode) 0.58f else 0.46f)", "Color(0xFFB58CFF).copy(alpha = if (darkMode) 0.46f else 0.36f)"),
        ("Color(0xFFFF55BE).copy(alpha = if (darkMode) 0.52f else 0.42f)", "Color(0xFFFF7FC8).copy(alpha = if (darkMode) 0.44f else 0.34f)"),
        ("Color(0xFFFFB45F).copy(alpha = if (darkMode) 0.30f else 0.34f)", "Color(0xFFFFD08A).copy(alpha = if (darkMode) 0.25f else 0.24f)"),
    ]
    for old, new in replacements:
        text = replace_once(text, old, new, f"palette {old}")

    # Make the top bar genuinely transparent-looking and glossy: a very faint
    # colour refraction layer plus a white specular highlight instead of a tinted slab.
    old_top = '''                        // CANDY_GLASS_V048: liquid-glass style. The aurora stays visible\n                        // through the bar; white highlights and color refraction provide\n                        // the glass edge instead of an opaque dark strip.\n                        modifier = Modifier\n                            .background(\n                                Brush.horizontalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.13f else 0.34f),\n                                        MaterialTheme.colorScheme.primary.copy(alpha = if (darkMode) 0.13f else 0.15f),\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = if (darkMode) 0.11f else 0.13f),\n                                        Color.White.copy(alpha = if (darkMode) 0.07f else 0.24f)\n                                    )\n                                )\n                            )\n                            .border(\n                                width = 0.8.dp,\n                                brush = Brush.horizontalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.40f else 0.68f),\n                                        MaterialTheme.colorScheme.primary.copy(alpha = 0.36f),\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = 0.34f),\n                                        Color.White.copy(alpha = if (darkMode) 0.22f else 0.48f)\n                                    )\n                                ),\n                                shape = RoundedCornerShape(0.dp)\n                            ),\n'''
    new_top = '''                        // CANDY_GLASS_V048: liquid-glass style. The aurora stays visible\n                        // through the bar; white highlights and color refraction provide\n                        // the glass edge instead of an opaque dark strip.\n                        // KAWAII_GLASS_V049: clearer glass with a brighter specular sheen.\n                        modifier = Modifier\n                            .background(\n                                Brush.horizontalGradient(\n                                    listOf(\n                                        MaterialTheme.colorScheme.primary.copy(alpha = if (darkMode) 0.07f else 0.06f),\n                                        Color.Transparent,\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = if (darkMode) 0.06f else 0.05f),\n                                        Color.Transparent\n                                    )\n                                )\n                            )\n                            .background(\n                                Brush.verticalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.24f else 0.38f),\n                                        Color.White.copy(alpha = if (darkMode) 0.08f else 0.14f),\n                                        Color.Transparent,\n                                        Color.White.copy(alpha = if (darkMode) 0.04f else 0.07f)\n                                    )\n                                )\n                            )\n                            .border(\n                                width = 0.7.dp,\n                                brush = Brush.horizontalGradient(\n                                    listOf(\n                                        Color.White.copy(alpha = if (darkMode) 0.52f else 0.76f),\n                                        MaterialTheme.colorScheme.primary.copy(alpha = 0.18f),\n                                        MaterialTheme.colorScheme.secondary.copy(alpha = 0.16f),\n                                        Color.White.copy(alpha = if (darkMode) 0.34f else 0.58f)\n                                    )\n                                ),\n                                shape = RoundedCornerShape(0.dp)\n                            ),\n'''
    text = replace_once(text, old_top, new_top, "clear glossy top glass")

    old_bottom = '''        Surface(\n            // FINISH_V046: continuous composer band through the gesture/navigation area.\n            // CANDY_GLASS_V048: transparent liquid-glass composer instead of a black slab.\n            color = Color.Transparent,\n            contentColor = MaterialTheme.colorScheme.onSurface,\n            tonalElevation = 0.dp,\n            modifier = Modifier\n                .fillMaxWidth()\n                .background(\n                    Brush.verticalGradient(\n                        listOf(\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.10f else 0.30f),\n                            MaterialTheme.colorScheme.surface.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.22f else 0.16f),\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.07f)\n                        )\n                    )\n                )\n                .border(\n                    width = 0.8.dp,\n                    brush = Brush.horizontalGradient(\n                        listOf(\n                            Color.White.copy(alpha = 0.38f),\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.30f),\n                            MaterialTheme.colorScheme.secondary.copy(alpha = 0.28f),\n                            Color.White.copy(alpha = 0.18f)\n                        )\n                    ),\n                    shape = RoundedCornerShape(0.dp)\n                )\n        ) {\n'''
    new_bottom = '''        Surface(\n            // FINISH_V046: continuous composer band through the gesture/navigation area.\n            // CANDY_GLASS_V048: transparent liquid-glass composer instead of a black slab.\n            // KAWAII_GLASS_V049: more transparent with a glossy top highlight.\n            color = Color.Transparent,\n            contentColor = MaterialTheme.colorScheme.onSurface,\n            tonalElevation = 0.dp,\n            modifier = Modifier\n                .fillMaxWidth()\n                .background(\n                    Brush.horizontalGradient(\n                        listOf(\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.045f),\n                            Color.Transparent,\n                            MaterialTheme.colorScheme.secondary.copy(alpha = 0.040f)\n                        )\n                    )\n                )\n                .background(\n                    Brush.verticalGradient(\n                        listOf(\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.18f else 0.28f),\n                            Color.White.copy(alpha = if (MaterialTheme.colorScheme.background.luminance() < 0.5f) 0.05f else 0.08f),\n                            Color.Transparent,\n                            Color.White.copy(alpha = 0.025f)\n                        )\n                    )\n                )\n                .border(\n                    width = 0.7.dp,\n                    brush = Brush.horizontalGradient(\n                        listOf(\n                            Color.White.copy(alpha = 0.52f),\n                            MaterialTheme.colorScheme.primary.copy(alpha = 0.16f),\n                            MaterialTheme.colorScheme.secondary.copy(alpha = 0.15f),\n                            Color.White.copy(alpha = 0.26f)\n                        )\n                    ),\n                    shape = RoundedCornerShape(0.dp)\n                )\n        ) {\n'''
    text = replace_once(text, old_bottom, new_bottom, "clear glossy bottom glass")

    path.write_text(text, encoding="utf-8")
    print("Applied KAWAII_GLASS_V049: sweeter palette + Pink × Purple + clearer glossy glass")


if __name__ == "__main__":
    patch_ui()
